// Name mapping between Danish country names and English names used in GeoJSON
export const countryNames = {

  "Albanien": "Albania",
  "Algeriet": "Algeria",
  "Antigua og Barbuda": "Antigua and Barbuda",
  "Armenien": "Armenia",
  "Armerikansk Samoa": "American Samoa",
  "Amerikanske Jomfruøer": "United States Virgin Islands",
  "Antugua og Barbuda": "Antigua and Barbuda",
  "Aserbaidsjan": "Azerbaijan",
  "Australien": "Australia",
  "Australsk Oceanien": "Australia",
  "Belgien": "Belgium",
  "Bouvetøen": "Bouvet Island",
  "Britisk Oceanien": "British Ocean Territories",
  "Bristiske Jomfruøer": "British Virgin Islands",
  "Britiske territorium i det indiske Ocean": "British Indian Ocean Territory",
  "Bosnien-Hercegovina": "Bosnia and Herzegovina",
  "Brasilien": "Brazil",
  "Bulgarien": "Bulgaria",
  "Cambodja": "Cambodia",
  "Caymanøerne": "Cayman Islands",
  "Centralafrikanske Republik": "Central African Republic",
  "Cocosøerne": "Cocos (Keeling) Islands",
  "Comorene": "Comoros",
  "Congo, Republikken": "Republic of the Congo",
  "Congo, Den Demokratiske Republik": "Democratic Republic of the Congo",
  "Cookøerne": "Cook Islands",
  "Curacao": "Curaçao",
  "Cypern": "Cyprus",
  "DDR": "Democratic Republic of the Congo",
  "Dominkanske Republik": "Dominican Republic",
  "Danmark": "Denmark",
  "Egypten": "Egypt",
  "Elfenbenskysten": "Ivory Coast",
  "Estland": "Estonia",
  "Etiopien": "Ethiopia",
  "Falklandsøerne": "Falkland Islands",
  "Filippinerne": "Philippines",
  "Finland": "Finland",
  "Forenede Arabiske Emirater": "United Arab Emirates",
  "Frankrig og Monaco": "France",
  "Fransk Guyana": "French Guiana",
  "Fransk Polynesien": "French Polynesia",
  "Franske besiddelser i det sydlige Indiske Ocean": "French Southern Territories",
  "Færøerne": "Faroe Islands",
  "Georgien": "Georgia",
  "Grækenland": "Greece",
  "Grønland": "Greenland",
  "Guniea-Bissau": "Guinea",
  "Heard- og MCDonaldøerne": "Heard Island and McDonald Islands",
  "Hongkong": "Hong Kong",
  "Indien": "India",
  "Indonesien": "Indonesia",
  "Irak": "Iraq",
  "Irland": "Ireland",
  "Island": "Iceland",
  "Italien": "Italy",
  "Juleøen": "Christmas Island",
  "Kanariske Øer": "Canary Islands",
  "Kap Verde": "Cape Verde",
  "Kasakhstan": "Kazakhstan",
  "Kina": "China",
  "Kirgistan": "Kyrgyzstan",
  "Kroatien": "Croatia",
  "Letland": "Latvia",
  "Libanon": "Lebanon",
  "Liberia": "Liberia",
  "Libyen": "Libya",
  "Liechtenstein": "Liechtenstein",
  "Litauen": "Lithuania",
  "Nordmakedonien": "North Macedonia",
  "Maldiverne": "Maldives",
  "Marokko": "Morocco",
  "Marchalløerne": "Marshall Islands",
  "Mikronesiske Stater": "Micronesia",
  "Mongoliet": "Mongolia",
  "Nederlandene": "Netherlands",
  "Nigeria": "Nigeria",
  "Nordkorea": "North Korea",
  "Norge": "Norway",
  "Ny Kaledonien": "New Caledonia",
  "Panamakanelzonen": "Panama",
  "Papua Ny Guinea": "Papua New Guinea",
  "Polen": "Poland",
  "Rumænien": "Romania",
  "Rusland": "Russia",
  "Saint Barthelemy": "Saint Barthélemy",
  "Salomonøerne": "Solomon Islands",
  "Saudi-Arabien": "Saudi Arabia",
  "Serbien": "Serbia",
  "Seychellerne": "Seychelles",
  "Skt. Helena": "Saint Helena",
  "Skt. Lucia": "Saint Lucia",
  "Skt. Lucia": "Saint Lucia",
  "Slovakiet": "Slovakia",
  "Slovenien": "Slovenia",
  "Spanien": "Spain",
  "Storbritannien": "United Kingdom",
  "Sverige": "Sweden",
  "Sydafrika": "South Africa",
  "Sydkorea": "South Korea",
  "Sydsudan": "South Sudan",
  "Syrien": "Syria",
  "Tadsjikistan": "Tajikistan",
  "Thailand": "Thailand",
  "Tjekkiet": "Czech Republic",
  "Tunesien": "Tunisia",
  "Turkmenistan": "Turkmenistan",
  "Tyrkiet": "Turkey",
  "Tyskland": "Germany",
  "Ukraine": "Ukraine",
  "Ungarn": "Hungary",
  "USA": "United States of America",
  "Usbekistan": "Uzbekistan",
  "Venezuela": "Venezuela",
  "Vietnam": "Vietnam",
  "Østrig": "Austria",
}